name: Jest Unit Tests
on: [push]
jobs:
  clone_and_test:
    name: Clone & test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Run test
        run: npm run jest:test
